# 启动端口号
server:
  post: 8000

# MySQL数据源配置
mysql:
  username: root      # 修改为自己数据库的用户名
  password: 123456    # 修改为自己数据库的密码
  url: tcp(localhost:3306)/shopping_db?charset=utf8&parseTime=True&loc=Local

# 图片路径配置
upload:
  savePath: /images/
  accessUrl: http://localhost:8000/image/

# JWT配置
jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h